# Generated by Django 2.0 on 2018-09-27 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='invoice/images/', validators=[django.core.validators.RegexValidator(regex='.pdf$')])),
                ('text', models.TextField()),
                ('number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(regex='\\d')])),
                ('operation_nature', models.CharField(max_length=255)),
                ('authorization_protocol', models.CharField(max_length=255)),
                ('acess_key', models.CharField(max_length=44, unique=True, validators=[django.core.validators.MinLengthValidator(44), django.core.validators.MaxLengthValidator(44), django.core.validators.RegexValidator(regex='\\d')])),
                ('state_registration', models.CharField(max_length=255)),
                ('emission_date', models.DateField()),
                ('entry_exit_datetime', models.DateField()),
                ('total_products_value', models.CharField(max_length=30)),
                ('total_invoice_value', models.CharField(max_length=30)),
                ('freight_value', models.CharField(default=',00', max_length=30)),
                ('icms_value', models.CharField(default=',00', max_length=30)),
                ('discount_value', models.CharField(default=',00', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('qtd', models.IntegerField()),
                ('unity_value', models.CharField(max_length=30)),
                ('total_value', models.CharField(max_length=30)),
                ('discount_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator(regex='\\d')])),
                ('county', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(13), django.core.validators.RegexValidator(regex='\\d')])),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14), django.core.validators.RegexValidator(regex='\\d')])),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator(regex='\\d')])),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.Receiver'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.Seller'),
        ),
    ]
