# Generated by Django 2.1.3 on 2018-11-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='invoice/images/')),
                ('number', models.CharField(blank=True, max_length=9, null=True)),
                ('operation_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('access_key', models.CharField(max_length=44, unique=True)),
                ('state_registration', models.CharField(blank=True, max_length=255, null=True)),
                ('emission_date', models.DateField(blank=True, null=True)),
                ('entry_exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_products_value', models.FloatField(blank=True, max_length=30, null=True)),
                ('total_invoice_value', models.FloatField(blank=True, null=True)),
                ('basis_calculation_icms', models.FloatField(blank=True, null=True)),
                ('freight_value', models.FloatField(blank=True, null=True)),
                ('insurance_value', models.FloatField(blank=True, null=True)),
                ('icms_value', models.FloatField(blank=True, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('basis_calculation_icms_st', models.FloatField(blank=True, null=True)),
                ('icms_value_st', models.FloatField(blank=True, null=True)),
                ('other_expenditure', models.FloatField(blank=True, null=True)),
                ('ipi_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(max_length=14, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('uf_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Receiver'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Seller'),
        ),
    ]
