# Generated by Django 2.0 on 2018-10-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='invoice/images/')),
                ('text', models.TextField()),
                ('number', models.CharField(blank=True, max_length=9)),
                ('operation_nature', models.CharField(blank=True, max_length=255)),
                ('authorization_protocol', models.CharField(blank=True, max_length=255)),
                ('access_key', models.CharField(max_length=44, unique=True)),
                ('state_registration', models.CharField(blank=True, max_length=255)),
                ('emission_date', models.DateField(blank=True)),
                ('entry_exit_datetime', models.DateTimeField(blank=True)),
                ('total_products_value', models.CharField(blank=True, max_length=30)),
                ('total_invoice_value', models.CharField(blank=True, max_length=30)),
                ('freight_value', models.CharField(blank=True, max_length=30)),
                ('icms_value', models.CharField(blank=True, max_length=30)),
                ('discount_value', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='invoice/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('qtd', models.IntegerField()),
                ('unity_value', models.CharField(max_length=30)),
                ('total_value', models.CharField(max_length=30)),
                ('discount_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('phone', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('uf_code', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.PDF'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Receiver'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Seller'),
        ),
    ]
