# Generated by Django 2.1.2 on 2018-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_invoice_value',
            field=models.FloatField(blank=True),
        ),
    ]
